import type { Metadata } from "next";
import NextAuth from "next-auth";
import { Inter } from "next/font/google";
import { SessionProvider, getSession } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  const session = await auth();
  // const { data: session } = getSession()
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          {children}
          </body>

      </html>
    </SessionProvider>
  );
}
